# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0007_auto_20160527_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='moment',
        ),
        migrations.AddField(
            model_name='moment',
            name='photo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='locator_cam.Photo'),
        ),
    ]
