# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0010_auto_20160527_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='moment',
            name='thumbnail_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
