# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0013_auto_20160605_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
