# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0015_auto_20160605_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_base64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='MomentPhoto',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='thumbnail_base64',
        ),
        migrations.AddField(
            model_name='momentthumbnail',
            name='moment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locator_cam.Moment'),
        ),
    ]
