# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0018_auto_20160610_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_managers',
            field=models.ManyToManyField(related_name='manage_channels', to='locator_cam.UserProfile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='membership_channels', to='locator_cam.UserProfile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator_cam.UserProfile'),
        ),
    ]
