# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0022_moment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_private_channel',
            field=models.BooleanField(default=False),
        ),
    ]
