# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0023_channel_is_private_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_private_channel',
            field=models.BooleanField(default=True),
        ),
    ]
