# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam', '0024_auto_20160625_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
