# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam_app', '0002_auto_20160525_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='user_profile',
            new_name='user',
        ),
    ]
