# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator_cam_app', '0003_auto_20160525_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ['-pub_time']},
        ),
    ]
